"""phase_2b_data_model

Revision ID: 973e9bef3510
Revises: 00b73b0a6635
Create Date: 2026-10-07 23:49:36.404510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '973e9bef3510'
down_revision: Union[str, Sequence[str], None] = '00b73b0a6635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind is not None and bind.dialect.name == "postgresql":
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
        op.execute('CREATE EXTENSION IF NOT EXISTS "vector";')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recruiters_company_name_idx', 'recruiters', ['company_name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('language', 'framework', 'database', 'tool', 'cloud', 'architecture', 'concept')", name='skills_category_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('skills_category_idx', 'skills', ['category'], unique=False)
    op.create_index('skills_name_idx', 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('candidate', 'admin')", name='users_role_check'),
    sa.CheckConstraint("status IN ('pending_verification', 'active', 'suspended', 'deleted')", name='users_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('users_email_idx', 'users', ['email'], unique=True)
    op.create_index('users_status_idx', 'users', ['status'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('activity_logs_user_created_idx', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('assessments',
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), server_default=sa.text('(15)'), nullable=False),
    sa.Column('passing_threshold', sa.Numeric(precision=4, scale=1), server_default=sa.text('(75.0)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('passing_threshold >= 0.0 AND passing_threshold <= 100.0', name='assessments_passing_threshold_check'),
    sa.CheckConstraint('time_limit_minutes > 0', name='assessments_time_limit_check'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('assessments_skill_id_idx', 'assessments', ['skill_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('diff_payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('human_approved', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_logs_created_at_idx', 'audit_logs', ['created_at'], unique=False)
    op.create_index('audit_logs_user_action_idx', 'audit_logs', ['user_id', 'action_type'], unique=False)
    op.create_table('career_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('primary_role_id', sa.String(length=64), nullable=False),
    sa.Column('secondary_role_id', sa.String(length=64), nullable=True),
    sa.Column('career_stage', sa.String(length=32), nullable=False),
    sa.Column('work_preference', sa.String(length=32), nullable=False),
    sa.Column('target_locations', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('years_of_experience', sa.Numeric(precision=3, scale=1), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("career_stage IN ('student', 'recent_graduate', 'early_career')", name='career_profiles_stage_check'),
    sa.CheckConstraint("work_preference IN ('remote', 'hybrid', 'onsite', 'flexible')", name='career_profiles_preference_check'),
    sa.CheckConstraint('years_of_experience >= 0.0', name='career_profiles_years_exp_check'),
    sa.ForeignKeyConstraint(['primary_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['secondary_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('career_profiles_primary_role_idx', 'career_profiles', ['primary_role_id'], unique=False)
    op.create_index('career_profiles_user_id_idx', 'career_profiles', ['user_id'], unique=True)
    op.create_table('career_readiness_scores',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('profile_completeness_factor', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('skill_proficiency_factor', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('roadmap_progress_factor', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('application_velocity_factor', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('top_next_actions', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('recorded_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('overall_score >= 0.0 AND overall_score <= 100.0', name='readiness_overall_score_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_date', name='uq_readiness_user_date')
    )
    op.create_index('readiness_user_date_idx', 'career_readiness_scores', ['user_id', 'recorded_date'], unique=True)
    op.create_table('interview_questions',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('talking_points_framework', sa.Text(), nullable=False),
    sa.Column('sample_high_performing_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'system_design', 'behavioral')", name='interview_questions_category_check'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('interview_questions_role_cat_idx', 'interview_questions', ['role_id', 'category'], unique=False)
    op.create_table('jobs',
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=64), server_default=sa.text("'seed'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('remote_type', sa.String(length=32), server_default=sa.text("'hybrid'"), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('description_markdown', sa.Text(), nullable=False),
    sa.Column('application_url', sa.String(length=512), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("experience_level IN ('internship', 'entry_level', 'junior', 'mid')", name='jobs_exp_level_check'),
    sa.CheckConstraint("remote_type IN ('remote', 'hybrid', 'onsite')", name='jobs_remote_type_check'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('jobs_company_title_loc_idx', 'jobs', ['company_name', 'title', 'location'], unique=False)
    op.create_index('jobs_role_active_idx', 'jobs', ['role_id', 'is_active'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("mime_type IN ('application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')", name='resumes_mime_type_check'),
    sa.CheckConstraint("status IN ('uploaded', 'parsing', 'parsed', 'failed')", name='resumes_status_check'),
    sa.CheckConstraint('file_size_bytes <= 10485760', name='resumes_file_size_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('resumes_user_id_idx', 'resumes', ['user_id'], unique=False)
    op.create_table('role_requirements',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.Column('min_proficiency', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("importance IN ('mandatory', 'preferred', 'bonus')", name='role_req_importance_check'),
    sa.CheckConstraint("min_proficiency IN ('basic', 'demonstrated', 'proficient', 'mastered')", name='role_req_min_proficiency_check'),
    sa.CheckConstraint('weight > 0.0', name='role_req_weight_check'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'skill_id', name='uq_role_requirements_role_skill')
    )
    op.create_index('role_req_role_skill_idx', 'role_requirements', ['role_id', 'skill_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('user_profiles_user_id_idx', 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET().with_variant(sa.String(length=45), 'sqlite'), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('user_sessions_token_hash_idx', 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index('user_sessions_user_id_idx', 'user_sessions', ['user_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('score_percentage', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'timed_out', 'abandoned')", name='assessment_attempts_status_check'),
    sa.CheckConstraint('score_percentage IS NULL OR (score_percentage >= 0.0 AND score_percentage <= 100.0)', name='assessment_attempts_score_check'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('assessment_attempts_assessment_id_idx', 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index('assessment_attempts_user_id_idx', 'assessment_attempts', ['user_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), server_default=sa.text("'intermediate'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("difficulty IN ('basic', 'intermediate', 'advanced')", name='assessment_questions_difficulty_check'),
    sa.CheckConstraint('correct_option_index >= 0 AND correct_option_index <= 3', name='assessment_questions_option_idx_check'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('assessment_questions_test_id_idx', 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('certifications',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=128), nullable=True),
    sa.Column('credential_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('certifications_profile_id_idx', 'certifications', ['career_profile_id'], unique=False)
    op.create_table('education',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=128), nullable=False),
    sa.Column('field_of_study', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('gpa IS NULL OR (gpa >= 0.0 AND gpa <= 4.0)', name='education_gpa_check'),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('education_profile_id_idx', 'education', ['career_profile_id'], unique=False)
    op.create_table('experience',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('bullet_points', postgresql.ARRAY(Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('experience_profile_id_idx', 'experience', ['career_profile_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('vector_score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('matched_skills', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('overall_score >= 0.0 AND overall_score <= 100.0', name='job_matches_score_check'),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_profile_id', 'job_id', name='uq_job_matches_profile_job')
    )
    op.create_index('job_matches_profile_job_idx', 'job_matches', ['career_profile_id', 'job_id'], unique=True)
    op.create_index('job_matches_profile_score_idx', 'job_matches', ['career_profile_id', 'overall_score'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_skill')
    )
    op.create_index('job_skills_job_skill_idx', 'job_skills', ['job_id', 'skill_id'], unique=True)
    op.create_table('projects',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('live_url', sa.String(length=255), nullable=True),
    sa.Column('bullet_points', postgresql.ARRAY(Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('projects_profile_id_idx', 'projects', ['career_profile_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('target_job_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('tailored_content', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('anti_hallucination_verified', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'archived')", name='resume_versions_status_check'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('resume_versions_resume_job_idx', 'resume_versions', ['resume_id', 'target_job_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_role_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=False),
    sa.Column('total_tasks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roadmaps_profile_active_idx', 'roadmaps', ['career_profile_id', 'is_active'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('readiness_percentage', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('met_skills', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('developing_skills', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(String(length=64)).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('explanation_narrative', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('readiness_percentage >= 0.0 AND readiness_percentage <= 100.0', name='skill_gaps_percentage_check'),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_profile_id', 'role_id', name='uq_skill_gaps_profile_role')
    )
    op.create_index('skill_gaps_profile_role_idx', 'skill_gaps', ['career_profile_id', 'role_id'], unique=True)
    op.create_table('user_skills',
    sa.Column('career_profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), server_default=sa.text('(0.20)'), nullable=False),
    sa.Column('proficiency_tier', sa.String(length=32), nullable=False),
    sa.Column('primary_source', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("primary_source IN ('self_reported', 'extracted', 'assessment', 'project_evidence')", name='user_skills_source_check'),
    sa.CheckConstraint("proficiency_tier IN ('unverified', 'demonstrated', 'proficient', 'mastered')", name='user_skills_tier_check'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='user_skills_confidence_check'),
    sa.ForeignKeyConstraint(['career_profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_profile_id', 'skill_id', name='uq_user_skills_profile_skill')
    )
    op.create_index('user_skills_confidence_idx', 'user_skills', ['confidence_score'], unique=False)
    op.create_index('user_skills_profile_skill_idx', 'user_skills', ['career_profile_id', 'skill_id'], unique=True)
    op.create_table('applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('current_status', sa.String(length=32), server_default=sa.text("'saved'"), nullable=False),
    sa.Column('tailored_resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("current_status IN ('saved', 'applied', 'screening', 'interviewing', 'offered', 'rejected', 'withdrawn')", name='applications_current_status_check'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tailored_resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_applications_user_job')
    )
    op.create_index('applications_job_idx', 'applications', ['job_id'], unique=False)
    op.create_index('applications_user_status_idx', 'applications', ['user_id', 'current_status'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_assessment_answers_attempt_q')
    )
    op.create_index('assessment_answers_attempt_q_idx', 'assessment_answers', ['attempt_id', 'question_id'], unique=True)
    op.create_table('assessment_results',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('strengths_summary', sa.Text(), nullable=False),
    sa.Column('weaknesses_summary', sa.Text(), nullable=False),
    sa.Column('remedial_milestones', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('confidence_lift', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index('assessment_results_attempt_idx', 'assessment_results', ['attempt_id'], unique=True)
    op.create_table('roadmap_phases',
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='roadmap_phases_order_idx_check'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roadmap_phases_roadmap_idx', 'roadmap_phases', ['roadmap_id', 'order_index'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('app_status_history_app_id_idx', 'application_status_history', ['application_id', 'changed_at'], unique=False)
    op.create_table('interviews',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('round_type', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("outcome IN ('pending', 'passed', 'failed', 'cancelled')", name='interviews_outcome_check'),
    sa.CheckConstraint("round_type IN ('recruiter_screen', 'technical_coding', 'system_design', 'behavioral', 'final_round')", name='interviews_round_type_check'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('interviews_app_scheduled_idx', 'interviews', ['application_id', 'scheduled_at'], unique=False)
    op.create_table('recruiter_contacts',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'recruiter_id', name='uq_recruiter_contacts_app_recruiter')
    )
    op.create_table('roadmap_tasks',
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('resource_urls', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('deliverable_requirement', sa.Text(), nullable=True),
    sa.Column('submission_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'skipped')", name='roadmap_tasks_status_check'),
    sa.CheckConstraint('estimated_hours > 0', name='roadmap_tasks_est_hours_check'),
    sa.CheckConstraint('order_index >= 0', name='roadmap_tasks_order_idx_check'),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roadmap_tasks_phase_idx', 'roadmap_tasks', ['phase_id', 'order_index'], unique=False)
    op.create_index('roadmap_tasks_status_idx', 'roadmap_tasks', ['status'], unique=False)
    op.create_table('interview_preparations',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_notes', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'question_id', name='uq_interview_prep_interview_q')
    )
    op.create_index('interview_prep_interview_q_idx', 'interview_preparations', ['interview_id', 'question_id'], unique=True)
    op.create_table('recruiter_messages',
    sa.Column('recruiter_contact_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('subject_line', sa.String(length=255), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('copied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("intent IN ('introduction', 'application_follow_up', 'informational_chat')", name='recruiter_messages_intent_check'),
    sa.CheckConstraint("status IN ('draft', 'copied_manually', 'archived')", name='recruiter_messages_status_check'),
    sa.ForeignKeyConstraint(['recruiter_contact_id'], ['recruiter_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recruiter_messages_contact_idx', 'recruiter_messages', ['recruiter_contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recruiter_messages_contact_idx', table_name='recruiter_messages')
    op.drop_table('recruiter_messages')
    op.drop_index('interview_prep_interview_q_idx', table_name='interview_preparations')
    op.drop_table('interview_preparations')
    op.drop_index('roadmap_tasks_status_idx', table_name='roadmap_tasks')
    op.drop_index('roadmap_tasks_phase_idx', table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_table('recruiter_contacts')
    op.drop_index('interviews_app_scheduled_idx', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('app_status_history_app_id_idx', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('roadmap_phases_roadmap_idx', table_name='roadmap_phases')
    op.drop_table('roadmap_phases')
    op.drop_index('assessment_results_attempt_idx', table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index('assessment_answers_attempt_q_idx', table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index('applications_user_status_idx', table_name='applications')
    op.drop_index('applications_job_idx', table_name='applications')
    op.drop_table('applications')
    op.drop_index('user_skills_profile_skill_idx', table_name='user_skills')
    op.drop_index('user_skills_confidence_idx', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index('skill_gaps_profile_role_idx', table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index('roadmaps_profile_active_idx', table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index('resume_versions_resume_job_idx', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index('projects_profile_id_idx', table_name='projects')
    op.drop_table('projects')
    op.drop_index('job_skills_job_skill_idx', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('job_matches_profile_score_idx', table_name='job_matches')
    op.drop_index('job_matches_profile_job_idx', table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('experience_profile_id_idx', table_name='experience')
    op.drop_table('experience')
    op.drop_index('education_profile_id_idx', table_name='education')
    op.drop_table('education')
    op.drop_index('certifications_profile_id_idx', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('assessment_questions_test_id_idx', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index('assessment_attempts_user_id_idx', table_name='assessment_attempts')
    op.drop_index('assessment_attempts_assessment_id_idx', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index('user_sessions_user_id_idx', table_name='user_sessions')
    op.drop_index('user_sessions_token_hash_idx', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('user_profiles_user_id_idx', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('role_req_role_skill_idx', table_name='role_requirements')
    op.drop_table('role_requirements')
    op.drop_index('resumes_user_id_idx', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('jobs_role_active_idx', table_name='jobs')
    op.drop_index('jobs_company_title_loc_idx', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('interview_questions_role_cat_idx', table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index('readiness_user_date_idx', table_name='career_readiness_scores')
    op.drop_table('career_readiness_scores')
    op.drop_index('career_profiles_user_id_idx', table_name='career_profiles')
    op.drop_index('career_profiles_primary_role_idx', table_name='career_profiles')
    op.drop_table('career_profiles')
    op.drop_index('audit_logs_user_action_idx', table_name='audit_logs')
    op.drop_index('audit_logs_created_at_idx', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('assessments_skill_id_idx', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('activity_logs_user_created_idx', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('users_status_idx', table_name='users')
    op.drop_index('users_email_idx', table_name='users')
    op.drop_table('users')
    op.drop_index('skills_name_idx', table_name='skills')
    op.drop_index('skills_category_idx', table_name='skills')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_index('recruiters_company_name_idx', table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
